-- MySQL Script generated by MySQL Workbench
-- Tue Jan 22 13:55:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ccvictoria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ccvictoria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ccvictoria` DEFAULT CHARACTER SET utf8 ;
USE `ccvictoria` ;

-- -----------------------------------------------------
-- Table `ccvictoria`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccvictoria`.`Usuario` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Tipo` INT NOT NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccvictoria`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccvictoria`.`Evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Lugar` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `FechaEvento` VARCHAR(45) NULL,
  `Horario` VARCHAR(45) NULL,
  `Imagen` VARCHAR(45) NULL,
  `Eventoscol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccvictoria`.`Promociones`
-- -----------------------------------------------------



-- -----------------------------------------------------
-- Table `ccvictoria`.`Giro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccvictoria`.`Giro` (
  `idGiro` INT NOT NULL AUTO_INCREMENT,
  `Categoria` INT NOT NULL,
  PRIMARY KEY (`idGiro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccvictoria`.`Tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccvictoria`.`Tienda` (
  `idTienda` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) NOT NULL,
  `Descripcion` VARCHAR(100) NULL,
  `Telefono` VARCHAR(20) NULL,
  `Horario` VARCHAR(30) NULL,
  `Imagen` VARCHAR(30) NULL,
  `No_Local` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idTienda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccvictoria`.`Empleo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccvictoria`.`Empleo` (
  `idEmpleos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Descripcion` VARCHAR(100) NULL,
  `Horario` VARCHAR(30) NULL,
  `Sueldo` VARCHAR(30) NULL,
  `Atencion` VARCHAR(30) NULL,
  PRIMARY KEY (`idEmpleos`))
ENGINE = InnoDB;





-- -----------------------------------------------------
-- Table `ccvictoria`.`Comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccvictoria`.`Comentarios` (
  `idComentarios` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(60) NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idComentarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccvictoria`.`Fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccvictoria`.`Fotos` (
  `idFotos` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFotos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccvictoria`.`Promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccvictoria`.`Promocion` (
  `idPromocion` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Descripcion` VARCHAR(100) NULL,
  `Imagen` VARCHAR(30) NULL,
  `Vigencia` VARCHAR(60) NULL,
  `Tienda_idTienda` INT NOT NULL,
  PRIMARY KEY (`idPromocion`),
  INDEX `fk_Promocion_Tienda1_idx` (`Tienda_idTienda` ASC),
  CONSTRAINT `fk_Promocion_Tienda1`
    FOREIGN KEY (`Tienda_idTienda`)
    REFERENCES `ccvictoria`.`Tienda` (`idTienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccvictoria`.`GiroTienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccvictoria`.`GiroTienda` (
  `Giro_idGiro` INT NOT NULL,
  `Tienda_idTienda` INT NOT NULL,
  PRIMARY KEY (`Giro_idGiro`, `Tienda_idTienda`),
  INDEX `fk_Giro_has_Tienda_Tienda1_idx` (`Tienda_idTienda` ASC),
  INDEX `fk_Giro_has_Tienda_Giro1_idx` (`Giro_idGiro` ASC),
  CONSTRAINT `fk_Giro_has_Tienda_Giro1`
    FOREIGN KEY (`Giro_idGiro`)
    REFERENCES `ccvictoria`.`Giro` (`idGiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Giro_has_Tienda_Tienda1`
    FOREIGN KEY (`Tienda_idTienda`)
    REFERENCES `ccvictoria`.`Tienda` (`idTienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccvictoria`.`TiendaEmpleo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccvictoria`.`TiendaEmpleo` (
  `Tienda_idTienda` INT NOT NULL,
  `Empleos_idEmpleos` INT NOT NULL,
  PRIMARY KEY (`Tienda_idTienda`, `Empleos_idEmpleos`),
  INDEX `fk_Tienda_has_Empleos_Empleos1_idx` (`Empleos_idEmpleos` ASC),
  INDEX `fk_Tienda_has_Empleos_Tienda1_idx` (`Tienda_idTienda` ASC),
  CONSTRAINT `fk_Tienda_has_Empleos_Tienda1`
    FOREIGN KEY (`Tienda_idTienda`)
    REFERENCES `ccvictoria`.`Tienda` (`idTienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tienda_has_Empleos_Empleos1`
    FOREIGN KEY (`Empleos_idEmpleos`)
    REFERENCES `ccvictoria`.`Empleo` (`idEmpleos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
